export const homestayInfo = [
    {
        height: "90px",
        width: "385px",
        border: true,
        title: "City, Property Name Or Location",
        ChevronDown: false,
        city: true,
        place: "Lalitpur",
        country: "Nepal",
        selectablePlaces: ["Satdobato", "Chabahil", "Boudha", "Thecho", "Kathmandu", "Pokhara"],
    },
    {
        height: "90px",
        width: "162px",
        border: true,
        title: "Check-In",
        ChevronDown: true,
        dateInfo: true,
    },
    {
        height: "90px",
        width: "162px",
        border: true,
        title: "Check-Out",
        ChevronDown: true,
        dateInfo: true,
    },
    {
        height: "90px",
        width: "245px",
        border: true,
        title: "Guests",
        ChevronDown: true,
        guestAndChildren: true,
    },
    {
        height: "90px",
        width: "full",
        border: false,
        title: "Price Per Night",
        ChevronDown: true,
        price: true,
        selectablePrices: ["Rs.0 - Rs.1500", "Rs.1500 - Rs.2500", "Rs.2500 - Rs.5000", "Rs.5000+"]
    },
]
